version: "3"
services:
    k8s:
        build: .
        volumes:
            - k8s-storage:/app/folder1/folder2
        ports:
            - 8989:8080
        environment:
            APP_FILE-PATH: app/folder1/folder2/file.log
volumes:
    k8s-storage: