apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s
      tier: client
  template:
    metadata:
      labels:
        app: k8s
        tier: client
    spec:
      containers:
        - name: k8s
          image: ooandioo/k8s:3.0
